version: '3.8'
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile.dev 
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
